<?php

use App\Http\Controllers\AccountApplicationController;
use App\Http\Controllers\AccountNotificationController;
use App\Http\Controllers\Api\Members;
use App\Http\Controllers\CharacterController;
use App\Http\Controllers\ContentReportController;
use App\Http\Controllers\DashboardProfileCustomizationController;
use App\Http\Controllers\GroupActivityApplicationController;
use App\Http\Controllers\GroupAvailabilityController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\GroupInviteController;
use App\Http\Controllers\GroupMembershipApplicationController;
use App\Http\Controllers\GroupMembershipController;
use App\Http\Controllers\GroupResourceController;
use App\Http\Controllers\GroupRunListController;
use App\Http\Controllers\ReportFeedbackController;
use App\Http\Controllers\Resources\ResourceGearsetController;
use App\Http\Controllers\Resources\ResourceImageController;
use App\Http\Controllers\RunDiscoveryController;
use App\Http\Controllers\UserController;
use App\Http\Middleware\IntegrationApiContext;
use App\Support\Integrations\IntegrationPermissions;
use Illuminate\Support\Facades\Route;

Route::prefix('integrations/v1')->name('api.members.')->middleware(IntegrationApiContext::class)->group(function () {
    Route::middleware(['integration.client:'.IntegrationPermissions::MEMBERS_READ, 'integration.member'])->group(function () {
        Route::get('me', [Members\AccountController::class, 'show'])->name('me');
        Route::get('characters', [Members\CharacterController::class, 'index'])->name('characters.index');
        Route::get('characters/{character}', [Members\CharacterController::class, 'show'])->whereNumber('character')->name('characters.show');
        Route::get('groups', [GroupController::class, 'search'])->name('groups.discover');
        Route::get('me/groups', [Members\GroupController::class, 'index'])->name('groups.index');
        Route::get('me/membership-requests', [Members\GroupController::class, 'requests'])->name('membership-requests.index');
        Route::get('groups/{group:slug}', [Members\GroupController::class, 'show'])->name('groups.show');
        Route::get('groups/{group:slug}/membership-application', [GroupMembershipApplicationController::class, 'create'])->name('membership-application.show');
        Route::get('groups/{group:slug}/notifications', [Members\GroupController::class, 'notifications'])->name('groups.notifications');
        Route::get('groups/{group:slug}/availability', [Members\GroupController::class, 'availability'])->name('groups.availability');
        Route::get('groups/{group:slug}/runs', [Members\RunController::class, 'group'])->name('groups.runs');
        Route::get('runs/lookups', [Members\RunController::class, 'lookups'])->name('runs.lookups');
        Route::get('runs', [RunDiscoveryController::class, 'discover'])->name('runs.discover');
        Route::get('me/runs', [Members\RunController::class, 'index'])->name('runs.index');
        Route::get('runs/{activity}', [Members\RunController::class, 'show'])->whereNumber('activity')->name('runs.show');
        Route::get('groups/{group:slug}/runs/{activity}/application', [GroupActivityApplicationController::class, 'show'])->whereNumber('activity')->name('application.form');
        Route::get('me/applications', [Members\RunController::class, 'applications'])->name('applications.index');
        Route::get('me/applications/{application}', [Members\RunController::class, 'application'])->whereNumber('application')->name('applications.show');
        Route::get('me/notifications', [Members\NotificationController::class, 'index'])->name('notifications.index');
        Route::get('me/notifications/summary', [Members\NotificationController::class, 'summary'])->name('notifications.summary');
        Route::get('me/report-feedback', [ReportFeedbackController::class, 'pending'])->name('feedback.index');
        Route::get('groups/{group:slug}/resources', [Members\ResourceController::class, 'index'])->name('resources.index');
        Route::get('groups/{group:slug}/collections/{collectionSlug}', [Members\ResourceController::class, 'collection'])->name('collections.show');
        Route::get('groups/{group:slug}/resources/{slug}', [Members\ResourceController::class, 'show'])->name('resources.show');
        Route::get('groups/{group:slug}/resources/{slug}/history', [GroupResourceController::class, 'history'])->name('resources.history');
        Route::get('resource-assets/{image:uuid}', [ResourceImageController::class, 'show'])->name('resource-assets.show');
        Route::get('gearset-icons/{icon}.png', [ResourceGearsetController::class, 'icon'])->where('icon', '[1-9][0-9]{0,5}')->name('gearset-icons.show');
    });

    Route::middleware(['integration.client:'.IntegrationPermissions::MEMBERS_WRITE, 'integration.member'])->group(function () {
        Route::patch('me/name', [UserController::class, 'changeUsername'])->name('me.name');
        Route::post('me/avatar', [UserController::class, 'changeProfilePicture'])->middleware('throttle:integration.upload')->name('me.avatar');
        Route::post('me/profile', [DashboardProfileCustomizationController::class, 'update'])->middleware('throttle:integration.upload')->name('me.profile');
        Route::put('me/privacy', [UserController::class, 'changePrivacySettings'])->name('me.privacy');
        Route::put('me/notification-preferences', [UserController::class, 'changeNotificationSettings'])->name('me.notifications');
        Route::put('me/time-display', [UserController::class, 'changeTimeDisplayPreference'])->name('me.time');
        Route::put('me/homepage', [UserController::class, 'changeHomepagePreference'])->name('me.homepage');
        Route::post('characters/claim', [CharacterController::class, 'exists'])->middleware('throttle:external.lookup')->name('characters.claim');
        Route::post('characters/verify', [CharacterController::class, 'verify'])->middleware('throttle:external.lookup')->name('characters.verify');
        Route::post('characters/{character}/refresh', [CharacterController::class, 'refreshCharacterData'])->middleware('throttle:external.lookup')->name('characters.refresh');
        Route::put('characters/{character}/primary', [CharacterController::class, 'makePrimary'])->name('characters.primary');
        Route::put('characters/{character}/preferred-class', [CharacterController::class, 'markPreferredClass'])->name('characters.class');
        Route::put('characters/{character}/preferred-phantom-job', [CharacterController::class, 'markPreferredPhantomJob'])->name('characters.phantom');
        Route::delete('characters/{character}', [CharacterController::class, 'destroy'])->name('characters.destroy');
        Route::post('groups/{group:slug}/join', [GroupMembershipController::class, 'join'])->middleware('throttle:membership.write')->name('groups.join');
        Route::post('groups/{group:slug}/leave', [GroupMembershipController::class, 'leave'])->name('groups.leave');
        Route::post('invites/{token}/accept', [GroupInviteController::class, 'accept'])->where('token', '[A-Za-z0-9-]{6,128}')->middleware(['throttle:invite', 'throttle:membership.write'])->name('invites.accept');
        Route::post('groups/{group:slug}/membership-application', [GroupMembershipApplicationController::class, 'store'])->middleware('throttle:membership.write')->name('membership-application.store');
        Route::put('groups/{group:slug}/membership-application', [GroupMembershipApplicationController::class, 'update'])->name('membership-application.update');
        Route::put('groups/{group:slug}/notifications', [GroupMembershipController::class, 'updateNotifications'])->name('groups.notifications.update');
        Route::put('groups/{group:slug}/availability', [GroupAvailabilityController::class, 'updateSchedule'])->name('groups.availability.update');
        Route::put('groups/{group:slug}/run-list', [GroupRunListController::class, 'store'])->name('groups.follow');
        Route::delete('groups/{group:slug}/run-list', [GroupRunListController::class, 'destroy'])->name('groups.unfollow');
        Route::put('runs/{activity}/saved', [RunDiscoveryController::class, 'save'])->name('runs.save');
        Route::delete('runs/{activity}/saved', [RunDiscoveryController::class, 'unsave'])->name('runs.unsave');
        Route::post('groups/{group:slug}/runs/{activity}/application', [GroupActivityApplicationController::class, 'store'])->middleware('throttle:application.submit')->name('application.store');
        Route::put('groups/{group:slug}/runs/{activity}/application', [GroupActivityApplicationController::class, 'update'])->middleware('throttle:application.submit')->name('application.update');
        Route::delete('me/applications/{application}', [AccountApplicationController::class, 'destroy'])->name('applications.withdraw');
        Route::post('me/notifications/read-all', [AccountNotificationController::class, 'readAll'])->name('notifications.read-all');
        Route::post('me/notifications/{notification}/read', [AccountNotificationController::class, 'open'])->name('notifications.read');
        Route::post('me/notification-broadcasts/{broadcast}/read', [AccountNotificationController::class, 'openBroadcast'])->name('notifications.broadcast-read');
        Route::post('me/report-feedback/{recipient}/acknowledge', [ReportFeedbackController::class, 'acknowledge'])->name('feedback.acknowledge');
        Route::post('reports', [ContentReportController::class, 'store'])->middleware('throttle:reports.submit')->name('reports.store');
    });
});
